# testdata.py
#
# contains example broadcast messages from N1MM+
#

TEST_DATA = [
    '''<?xml version="1.0"?>
   <contactinfo>
           <contestname>FD</contestname>
           <contestnr>1</contestnr>
           <timestamp>2016-03-27 14:32:00</timestamp>
           <mycall>N1KDO</mycall>
           <band>7</band>
           <rxfreq>719601</rxfreq>
           <txfreq>719601</txfreq>
           <operator>N1KDO</operator>
           <mode>LSB</mode>
           <call>W4OO</call>
           <countryprefix>K</countryprefix>
           <wpxprefix>W4</wpxprefix>
           <stationprefix>N1KDO</stationprefix>
           <continent>NA</continent>
           <snt>59</snt>
           <sntnr>6</sntnr>
           <rcv>59</rcv>
           <rcvnr>0</rcvnr>
           <gridsquare></gridsquare>
           <exchange1>1D</exchange1>
           <section>GA</section>
           <comment></comment>
           <qth></qth>
           <name></name>
           <power></power>
           <misctext></misctext>
           <zone>5</zone>
           <prec></prec>
           <ck>0</ck>
           <ismultiplier1>0</ismultiplier1>
           <ismultiplier2>0</ismultiplier2>
           <ismultiplier3>0</ismultiplier3>
           <points>1</points>
           <radionr>1</radionr>
           <RoverLocation></RoverLocation>
           <RadioInterfaced>0</RadioInterfaced>
           <NetworkedCompNr>0</NetworkedCompNr>
           <IsOriginal>True</IsOriginal>
           <NetBiosName>OTTER5</NetBiosName>
           <IsRunQSO>0</IsRunQSO>
   </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:35:25</timestamp>
            <mycall>N1KDO</mycall>
            <band>3.5</band>
            <rxfreq>374500</rxfreq>
            <txfreq>374500</txfreq>
            <operator>N1KDO</operator>
            <mode>LSB</mode>
            <call>N2OJG</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>N2</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>7</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>1D</exchange1>
            <section>NC</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:36:33</timestamp>
            <mycall>N1KDO</mycall>
            <band>3.5</band>
            <rxfreq>374500</rxfreq>
            <txfreq>374500</txfreq>
            <operator>KE4UW</operator>
            <mode>LSB</mode>
            <call>W1AW</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>W1</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>8</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>1D</exchange1>
            <section>CT</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:37:22</timestamp>
            <mycall>N1KDO</mycall>
            <band>1.8</band>
            <rxfreq>184000</rxfreq>
            <txfreq>184000</txfreq>
            <operator>KE4UW</operator>
            <mode>LSB</mode>
            <call>W0WK</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>W0</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>9</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>4E</exchange1>
            <section>IA</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>4</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:38:05</timestamp>
            <mycall>N1KDO</mycall>
            <band>14</band>
            <rxfreq>1423100</rxfreq>
            <txfreq>1423100</txfreq>
            <operator>KE4UW</operator>
            <mode>USB</mode>
            <call>W6LE</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>W6</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>10</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>21A</exchange1>
            <section>LAX</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>3</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:38:46</timestamp>
            <mycall>N1KDO</mycall>
            <band>21</band>
            <rxfreq>2133319</rxfreq>
            <txfreq>2133319</txfreq>
            <operator>KE4UW</operator>
            <mode>USB</mode>
            <call>W2FU</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>W2</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>11</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>1D</exchange1>
            <section>ENY</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:39:25</timestamp>
            <mycall>N1KDO</mycall>
            <band>28</band>
            <rxfreq>2815000</rxfreq>
            <txfreq>2815000</txfreq>
            <operator>KE4UW</operator>
            <mode>USB</mode>
            <call>W3AO</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>W3</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>12</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>33A</exchange1>
            <section>MDC</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:39:25</timestamp>
            <mycall>N1KDO</mycall>
            <band>28</band>
            <rxfreq>2815000</rxfreq>
            <txfreq>2815000</txfreq>
            <operator>KE4UW</operator>
            <mode>USB</mode>
            <call>W3AO</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>W3</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>12</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>33A</exchange1>
            <section>MDC</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:42:00</timestamp>
            <mycall>N1KDO</mycall>
            <band>50</band>
            <rxfreq>5012500</rxfreq>
            <txfreq>5012500</txfreq>
            <operator>KE4UW</operator>
            <mode>USB</mode>
            <call>W4IMD</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>W4</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>13</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>1D</exchange1>
            <section>GA</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:42:53</timestamp>
            <mycall>N1KDO</mycall>
            <band>144</band>
            <rxfreq>14422500</rxfreq>
            <txfreq>14422500</txfreq>
            <operator>KE4UW</operator>
            <mode>USB</mode>
            <call>W4NH</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>W4</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>14</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>4A</exchange1>
            <section>NC</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
        <contestname>FD</contestname>
        <contestnr>1</contestnr>
        <timestamp>2016-03-27 16:43:56</timestamp>
        <mycall>N1KDO</mycall>
        <band>144</band>
        <rxfreq>14422500</rxfreq>
        <txfreq>14422500</txfreq>
        <operator>KE4UW</operator>
        <mode>CW</mode>
        <call>W4IMD</call>
        <countryprefix>K</countryprefix>
        <wpxprefix>W4</wpxprefix>
        <stationprefix>N1KDO</stationprefix>
        <continent>NA</continent>
        <snt>599</snt>
        <sntnr>15</sntnr>
        <rcv>599</rcv>
        <rcvnr>0</rcvnr>
        <gridsquare></gridsquare>
        <exchange1>1D</exchange1>
        <section>GA</section>
        <comment></comment>
        <qth></qth>
        <name></name>
        <power></power>
        <misctext></misctext>
        <zone>5</zone>
        <prec></prec>
        <ck>0</ck>
        <ismultiplier1>0</ismultiplier1>
        <ismultiplier2>0</ismultiplier2>
        <ismultiplier3>0</ismultiplier3>
        <points>2</points>
        <radionr>1</radionr>
        <RoverLocation></RoverLocation>
        <RadioInterfaced>0</RadioInterfaced>
        <NetworkedCompNr>0</NetworkedCompNr>
        <IsOriginal>True</IsOriginal>
        <NetBiosName>OTTER5</NetBiosName>
        <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:44:49</timestamp>
            <mycall>N1KDO</mycall>
            <band>50</band>
            <rxfreq>5027600</rxfreq>
            <txfreq>5027600</txfreq>
            <operator>KE4UW</operator>
            <mode>PSK31</mode>
            <call>W1CUM</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>W1</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>599</snt>
            <sntnr>16</sntnr>
            <rcv>599</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>2A</exchange1>
            <section>VT</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>2</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER11</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 16:45:20</timestamp>
            <mycall>N1KDO</mycall>
            <band>21</band>
            <rxfreq>2107000</rxfreq>
            <txfreq>2107000</txfreq>
            <operator>KE4UW</operator>
            <mode>RTTY</mode>
            <call>WR1TTY</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>WR1</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>599</snt>
            <sntnr>17</sntnr>
            <rcv>599</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>1D</exchange1>
            <section>DE</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>2</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 17:29:58</timestamp>
            <mycall>N1KDO</mycall>
            <band>144</band>
            <rxfreq>14652000</rxfreq>
            <txfreq>14652000</txfreq>
            <operator>KE4UW</operator>
            <mode>FM</mode>
            <call>KZ4ZZZ</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>KZ4</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>18</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>1D</exchange1>
            <section>GA</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 17:30:23</timestamp>
            <mycall>N1KDO</mycall>
            <band>420</band>
            <rxfreq>44600000</rxfreq>
            <txfreq>44600000</txfreq>
            <operator>KE4UW</operator>
            <mode>FM</mode>
            <call>KX4XXX</call>
            <countryprefix>K</countryprefix>
            <wpxprefix>KX4</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>19</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>4F</exchange1>
            <section>AL</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>5</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER11</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
    '''<?xml version="1.0"?>
    <contactinfo>
            <contestname>FD</contestname>
            <contestnr>1</contestnr>
            <timestamp>2016-03-27 17:30:44</timestamp>
            <mycall>N1KDO</mycall>
            <band>420</band>
            <rxfreq>43200000</rxfreq>
            <txfreq>43200000</txfreq>
            <operator>KE4UW</operator>
            <mode>USB</mode>
            <call>KL7ABC</call>
            <countryprefix>KL</countryprefix>
            <wpxprefix>KL7</wpxprefix>
            <stationprefix>N1KDO</stationprefix>
            <continent>NA</continent>
            <snt>59</snt>
            <sntnr>20</sntnr>
            <rcv>59</rcv>
            <rcvnr>0</rcvnr>
            <gridsquare></gridsquare>
            <exchange1>1D</exchange1>
            <section>AK</section>
            <comment></comment>
            <qth></qth>
            <name></name>
            <power></power>
            <misctext></misctext>
            <zone>1</zone>
            <prec></prec>
            <ck>0</ck>
            <ismultiplier1>0</ismultiplier1>
            <ismultiplier2>0</ismultiplier2>
            <ismultiplier3>0</ismultiplier3>
            <points>1</points>
            <radionr>1</radionr>
            <RoverLocation></RoverLocation>
            <RadioInterfaced>0</RadioInterfaced>
            <NetworkedCompNr>0</NetworkedCompNr>
            <IsOriginal>True</IsOriginal>
            <NetBiosName>OTTER5</NetBiosName>
            <IsRunQSO>0</IsRunQSO>
    </contactinfo>''',
]
